export const LOAD_PRODUCTS_LIST = 'LOAD_PRODUCTS_LIST';
export const SEARCH_PRODUCTS = 'SEARCH_PRODUCTS';
export const LOAD_CATEGORIES_LIST = 'LOAD_CATEGORIES_LIST';
export const LOAD_CATEGORY = 'LOAD_CATEGORY';
